### ISSUE TITLE
Missing judgement graphics

### ISSUE THREAD

**Issue by marysiamzawka** [gibgib1212/Rm-skin#1]
https://www.youtube.com/watch?v=Sd-M3WOqrFM
Judgements and numbers showcased in this video are missing from the release

**Comment by gibgib1212** [comment]
Dear Marysia Mżawka

Thanks a bunch for your query.
This sample video is from an earlier version. In a subsequent update, I
removed the judgements and numbers you mentioned.
The reason for this is that the origin of the above image files is unknown
and, therefore, the possibility of unintentional copyright infringement is
considered.

So, I'm sorry, but if you really want the judges in R-skin format, please
process the images yourself.


2023年8月20日(日) 20:13 Marysia Mżawka ***@***.***>:
